const buttonIds = Object.freeze({
	POAP_OPT_IN_YES: 'GET_DM_YES',
	POAP_OPT_IN_NO: 'GET_DM_NO',
	POAP_REPORT_SPAM: 'REPORT_SPAM',
	POAP_CONFIG_APPROVE: 'APPROVE_CONFIG',
	POAP_CONFIG_REMOVE: 'REMOVE_CONFIG',
	ACCOUNT_UNLINK_APPROVE: 'UNLINK_ACCOUNT_YES',
	ACCOUNT_UNLINK_REJECT: 'UNLINK_ACCOUNT_NO',
});

export default buttonIds;
