export default Object.freeze({
	FIRST_QUEST_ROLES : {
		verified: process.env.DISCORD_ROLE_FIRST_QUEST_START,
		first_quest_welcome: process.env.DISCORD_ROLE_FIRST_QUEST_WELCOME,
		first_quest_membership: process.env.DISCORD_ROLE_FIRST_QUEST_MEMBERSHIP,
		firehose: process.env.DISCORD_ROLE_FIRST_QUEST_FIREHOSE,
		first_quest_scholar: process.env.DISCORD_ROLE_FIRST_QUEST_SCHOLAR,
		first_quest_guest_pass: process.env.DISCORD_ROLE_FIRST_QUEST_GUEST_PASS,
		first_quest: process.env.DISCORD_ROLE_FIRST_QUEST,
		first_quest_complete: process.env.DISCORD_ROLE_FIRST_QUEST_COMPLETE,
	},

	FIRST_QUEST_DB_DOCUMENT_ID: '61743936a3f05763f8d90719',

	FIRST_QUEST_INIT : {
		'fq1': 'Hello! Welcome to BanklessDAO. We\'re glad you\'re here 🙂 \\n\\nWe would like to encourage all new members to activate **2 factor authentication (2FA)**, See how it\'s done here: <https://support.discord.com/hc/en-us/articles/219576828-Setting-up-Two-Factor-Authentication>\\n\\n**The easiest way to get started with your Bankless DAO journey is by completing the first quest. During your first quest I will walk you through everything you need, to get up and running with Bankless DAO. When you\'re ready to start, let me know by clicking the 🏦 emoji at the end of this message.**\\n\\nHere are the TOP 5 THINGS you should know: \\n1. To verify your full membership, follow these instructions. You NEED to have 35,000 BANK in your wallet. \\n<https://discordapp.com/channels/834499078434979890/834499890569543720/846235762109186058> \\n\\n2. Notion is our source of information. If you\\\'re looking for something, it\\\'s probably there. \\n<https://www.notion.so/bankless/BanklessDAO-Wiki-82ba81e7da1c42adb7c4ab67a4f22e8f> \\n\\n3. Our Community Calls are every Friday at 15:00 UTC. You can add any BanklessDAO meeting to your personal calendar. \\n<https://www.notion.so/bankless/Meetings-Calendar-794ea323caad40e19a8a22bc2ec6edb6> \\n\\n4. Subscribe to our Newsletter: \\n<https://banklessdao.substack.com/> \\n\\n5. Here\\\'s a quick cheatsheet on how to start engaging with the community \\n<https://www.notion.so/bankless/Getting-Started-Cheat-Sheet-2521514971984ad4b440e00b3a7a6312> \\n\\n**Start your first quest now:** \\n\\n',
		'fq2': '**>> Important message: Support will never send you a Direct Message offering DAO assistance. You must request it by your DM. <<**\\n**>> Never ever ever reveal your private keys.<<**\\n\\n-----------------------------------------\\n\\nWelcome to your First Quests. First Quests were created by BanklessDAO members to give you a short and effective onboarding experience that will introduce you to Bankless, the tools we use to manage our community, and how to get involved. All new members start with these First Quests. After reading this message, you\\\'ll have already completed your first quest for Bankless - joining the discord. \\n\\n-----------------------------------------\\n\\nReact to this message with the 🏦 emoji to access your next quest. \\n\\n',
		'fq3': 'Welcome! The purpose of this quest is to choose your membership path.\\n\\n-----------------------------------------\\n\\nParticipating in the DAO has no financial requirements.\\n\\nHowever, obtaining Level 1 membership gives you access to our Membership Perks. Currently these perks are limited, but we will continue to add more, like an NFT focused channel, NFT raffles, PoolTogether pods, early access to media, and more!\\n\\nIn the Discord, Level 1 members have verified they own at least 35,000 $BANK, while Level 0 members have not. This distinction is important as Level 1 members are able to participate in most channels, while Level 0 members are only able to write in a few.\\n\\nIf you have the minimum 35,000 $BANK, follow the instructions in <#834499890569543720> to get your tags and permissions. \\nOnce verified, you\\\'ll have access to all channels. Welcome aboard! Come say hello in <#838790540899254303> and join a guild from <#851864032796999744>\\n\\nIf you do NOT have the minimum 35,000 $BANK, don’t worry! There is an upcoming quest where you will obtain a guest pass. Many of us have started with 0 $BANK and have earned our 35,000 in only a few weeks. \\n\\nReact to this message BELOW with the 🏦 emoji to access your next quest.',
		'fq4': 'Welcome! The purpose of this quest is to ease into our primary communication channel, Discord.\\n\\nIf you’ve never used Discord before or are unfamiliar with its layout, please watch this short video:\\n<https://www.loom.com/share/a5e35879f22b4a0eb0bbc621458cb28c>\\n\\n-----------------------------------------\\n\\nYou can only view a **small subset** of all discord channels. We\\\'re doing this because diving in right away can be like drinking from a firehose :firehose:  .\\n\\nRight now, let’s focus on the broader picture. Discord operates using text and audio channels, nested within “categories” that have different permissions. Let’s look at some of the important categories within the BanklessDAO Discord:\\n🏦 Welcome (Level 0): Channels in this category are open to anyone that joins the Discord.\\n🏦 BanklessDAO in Bites: Quickly plug yourself into meetings, polls, forums, and more\\n🏦 General (Level 1): The main hangout for general DAO conversations\\n🏦 Community Call: The CC is a vital source of information. Join us every Friday at 15:00 UTC\\n🏦 Guilds: We have a slew of different guilds. Participating in a Guild is the best way to get active. \\n\\n----------------------------------------- \\n\\nTake a few minutes to explore these channels with the **following video** and get a sense for how we communicate! \\n\\n-----------------------------------------\\n\\nReact to this message with the ✏️  emoji to access your next quest. \\n',
		'fq5': 'Welcome! The purpose of this quest is to introduce you to why BanklessDAO exists.\\n\\n----------------------------------------- \\n\\nBankless is a movement for pioneers seeking liberation from the tyranny of the traditional financial system. Going Bankless means adopting decentralized, permissionless, and censorship-resistant technology. Through these means, we will achieve financial self-sovereignty, security, and prosperity.\\nBanklessDAO is the decentralized autonomous organization that acts as a steward of the Bankless Movement progressing the world towards a future of greater freedom.\\n🔸 **Mission:** We will help the world go Bankless by creating user-friendly onramps for people to discover decentralized financial technologies through education, media, and culture.\\n🔸 **Vision:** To live in a world where anyone with an internet connection has access to the financial tools needed to achieve financial independence\\n🔸 **Values:** Education, Integrity, Decentralized Governance, and Culture\\n\\n🔴 **Education:** We learn from each other. We seek to become a trusted guide that empowers people all over the globe to adopt decentralized finance by sharing accurate, truthful, and objective information.\\n🔴 **Integrity:** We operate transparently and build trust through radically public discourse and financial auditability.\\n🔴 **Decentralized Governance:** We put decision making into the hands of the collective. We create legitimacy through an environment where the best ideas win.\\n🔴 **Culture:** We reward action and embrace risk. We empower our community to continually drive new initiatives by providing a space to self-organize and quickly move from idea to action.\\n\\n-----------------------------------------\\n\\nSee below video for a summary. \\n\\n-----------------------------------------\\n\\nReact to this message with the ✏️  emoji to access your next quest.',
		'fq6': 'Welcome! The purpose of this quest is to provide a pathway for members without 35,000 $BANK to get involved using our `Guest Pass`.\\n\\n-----------------------------------------\\n\\nWe do not want the 35,000 $BANK entry cost to prohibit people from contributing to our mission of helping the world go bankless. So, we created the `Guest Pass` to allow the same privileges as `Level 1` members (except for access to the Membership Perks category).\\n\\nOnce you receive a `Guest Pass`, you can retain it by participating in the Discord. At a minimum, you will be expected to contribute to discussions, all the way up to attending weekly Guild calls and completing bounties. Guest passes are not permanent, and inactivity will cause your `Guest Pass` to be revoked.\\n\\n**To obtain a `Guest Pass`, navigate to the <#845036405667397662>  and introduce yourself, your background, what interests you in the DAO, and any skills or ways you think you might want to or be able to contribute! There are unlimited ways to contribute/participate, you don’t have to be a Shadowy Super Coder to join!**\\n\\nOnce you have a Guest Pass, you\\\'ll have access to all channels. Welcome aboard! Come say hello in <#838790540899254303> and join a guild from <#851864032796999744>. If it feels overwhelming right now, don’t stress, just drop in to the intro channel and take it from there with guidance! \\n\\n-----------------------------------------\\n\\nReact to this message with the ✏️  emoji to access your next quest. \\n',
		'fq7': 'Welcome! You’ve made it to your true **first quest**, should you choose to accept (you should!)\\n\\n-----------------------------------------\\n\\nEven though you’ve made it to the DAO and have familiarized with our Discord, it can still feel like you’re drinking from a firehose :firehose: .\\n\\nTo stay up to date, our Writer’s Guild has consistently produced a high-quality weekly rollup on all DAO activities.\\n\\nYour first quest on this journey west, O\\\' fellow Bankless adventurer is to sign up and be the first in line to learn about BanklessDAO alpha, such as access to the discussions about NFT sales, Metafactory merch drops, inter-DAO projects, and so much more!\\nhttps://banklessdao.substack.com/\\n\\nOnce you’ve completed your first quest, react with a 🤠 \\nBankless DAO\\nThe revolution will not be banked. This is the official newsletter of the Bankless DAO. Expect updates on the weekly.\\n',
		'fq8': '**Congratulations! You have reached the end of first quest**. \\n\\nIf you want to repeat first quest, you can reset your role and start over by responding with **!first-quest**.\\n',
	},
});